In [8]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해
import numpy as np
docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()

In [9]:
# 총 문서의 수
N = len(docs) 

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        df += t in doc
    return log(N/(df+1))

def tfidf(t, d):
    return tf(t,d)* idf(t)

In [10]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)

In [11]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
idf_

IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [12]:
result = []
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [29]:
x = tfidf_

In [34]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

In [37]:
df2 = pd.DataFrame()
df2['x'] = [0.4 , 0.1 , 0.6 , 0.3 ]
df2['y'] = [0.6, 0.1 , 0.1, 0.7 ]

In [39]:
0.34**1/2

0.17

In [41]:
0.3 * 0.01

0.003

In [45]:
0.58892 - 0.58309

0.005830000000000002

In [ ]:
( (0.4 - 0.097)**2 + (0.6 - 0.095)**2)**0.5

In [43]:
( (0.4 - 0.103)**2 + (0.6 - 0.105)**2)**0.5

0.5889261413793754

In [35]:
euclidean_distances(tfidf_)

array([[0.        , 0.75047584, 1.39209371, 1.44476088],
       [0.75047584, 0.        , 1.09963128, 1.29986229],
       [1.39209371, 1.09963128, 0.        , 1.6532722 ],
       [1.44476088, 1.29986229, 1.6532722 , 0.        ]])

In [38]:
euclidean_distances(df2)

array([[0.        , 0.58309519, 0.53851648, 0.14142136],
       [0.58309519, 0.        , 0.5       , 0.63245553],
       [0.53851648, 0.5       , 0.        , 0.67082039],
       [0.14142136, 0.63245553, 0.67082039, 0.        ]])

In [31]:
x.cov().to_excel('cov.xlsx')

In [32]:
x.to_excel('data.xlsx')

In [21]:
X = tfidf_.values

In [28]:
np.square(X)

array([[0.        , 0.        , 0.        , 0.08276097, 0.        ,
        0.48045301, 0.08276097, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.08276097, 0.08276097,
        0.        , 0.08276097, 0.        , 0.        ],
       [0.        , 0.48045301, 0.48045301, 0.        , 0.3310439 ,
        0.        , 0.        , 0.        , 0.        ],
       [0.48045301, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.48045301, 0.48045301]])

In [23]:
sum_X = np.sum(np.square(X), 1)

In [27]:
sum_X

array([0.64597496, 0.24828292, 1.29194993, 1.44135904])

In [24]:
-2 * np.dot(X, X.T)

array([[-1.29194993, -0.3310439 , -0.        , -0.        ],
       [-0.3310439 , -0.49656585, -0.3310439 , -0.        ],
       [-0.        , -0.3310439 , -2.58389985, -0.        ],
       [-0.        , -0.        , -0.        , -2.88271808]])

In [25]:
sum_X

array([0.64597496, 0.24828292, 1.29194993, 1.44135904])

In [26]:
np.add(-2 * np.dot(X, X.T), sum_X)

array([[-0.64597496, -0.08276097,  1.29194993,  1.44135904],
       [ 0.31493106, -0.24828292,  0.96090603,  1.44135904],
       [ 0.64597496, -0.08276097, -1.29194993,  1.44135904],
       [ 0.64597496,  0.24828292,  1.29194993, -1.44135904]])

In [16]:
D = np.add(np.add(-2 * np.dot(X, X.T), sum_X).T, sum_X)

ValueError: Data must be 1-dimensional